# Copyright (c) 2023 SolarWinds, LLC.
# All rights reserved.

name: Ruby Gem to Github Package

on:
  workflow_dispatch:
    inputs:
      rubygem-path:
        required: true
        description: 'The path that package you want to publish (should include /)'
        # metrics_sdk/
        # metrics_api/
        # exporter/otlp/

      rubygem-name:
        required: true
        description: 'The gem to publish, e.g. opentelemetry-instrumentation-<???>'
        # opentelemetry-metrics-sdk
        # opentelemetry-metrics-api
        # opentelemetry-exporter-otlp

      version:
        required: true
        description: 'The gem version to publish'

jobs:
  build:
    name: Build + Publish to Github Package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby 3.1 and bundle
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install gems
        run: |
          cd ${{ github.event.inputs.rubygem-path }}
          echo 'gem: --no-document' >> ~/.gemrc
          bundle install

      - name: Setup secrets
        run: |
          mkdir ~/.gem
          echo -e "---\n:github: Bearer $GITHUB_SECRET_TOKEN" >> ~/.gem/credentials
          chmod 0600 ~/.gem/credentials
        env:
          GITHUB_SECRET_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build gem and publish to github package
        id: gemstep
        run:  |
          gem_name=${{ github.event.inputs.rubygem-name }}
          gem_version=${{ github.event.inputs.version }}
          cd ${{ github.event.inputs.rubygem-path }}
          gem build "${gem_name}.gemspec"
          gem push --key github --host https://rubygems.pkg.github.com/solarwinds "${gem_name}-${gem_version}.gem"
